name: hello world workflow

on:
  push:
     branches: 
          - main
  pull_request:
     branches:
          - main
  workflow_dispatch:

jobs: 
  hello: 
     runs-on: ubuntu_latest
     steps:
       - uses: actions/checkout@v3
       - name: hello world
         run: echo "hello world"
         shell: bash
  good_bye:
      runs-on: ubuntu_latest
      steps:
        - name: good bye
          run: echo "goodbye"
          shell: bash



